name: macOS Build Qt 6.9 Static and Upload to Release (macOS Universal, qt-cmake)
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install \
            cmake \
            ninja \
            perl \
            python3 \
            pkg-config \
            freetype \
            fontconfig \
            libpng \
            jpeg \
            zlib \
            pcre2 \
            harfbuzz \
            git \
            wget

      - name: Download Qt 6.9.0 source
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.9/6.9.0/single/qt-everywhere-src-6.9.0.tar.xz
          tar xf qt-everywhere-src-6.9.0.tar.xz

      - name: Configure Qt with qt-cmake (static, universal)
        run: |
          mkdir qt-build
          cd qt-build

          export CMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          cmake ../qt-everywhere-src-6.9.0 \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=$(pwd)/qt6-static-install \
            -DCMAKE_OSX_ARCHITECTURES="${CMAKE_OSX_ARCHITECTURES}" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
            -DQT_FEATURE_static=ON \
            -DQT_FEATURE_shared=OFF \
            -DQT_BUILD_EXAMPLES=OFF \
            -DQT_BUILD_TESTS=OFF \
            -DFEATURE_optimize_size=ON \
            -DFEATURE_system_zlib=OFF \
            -DFEATURE_system_png=OFF \
            -DFEATURE_system_jpeg=OFF \
            -DFEATURE_system_pcre2=OFF \
            -DFEATURE_system_doubleconversion=OFF \
            -DFEATURE_system_freetype=OFF \
            -DFEATURE_system_harfbuzz=OFF \
            -DFEATURE_pkg_config=ON \
            -DQT_BUILD_QDOC=OFF \
            -DFEATURE_pch=OFF
  
      - name: Build and install Qt
        run: |
          cd qt-build
          cmake --build . --parallel
          cmake --install . --prefix qt6-static-install

      - name: Package Qt
        run: |
          cd qt-build
          tar -czf qt6.9.0-macos-universal-static.tar.gz qt6-static-install

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt6.9.0-static-macos-universal
          name: Qt 6.9.0 Static macOS Universal
          files: qt-build/qt6.9.0-macos-universal-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}