name: Build QtBase 6.9.0 Static and Upload to Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgl1-mesa-dev \
            libxcb-icccm4-dev \
            libxcb-xinput-dev \
            ninja-build \
            python3 \
            perl \
            cmake \
            curl \
            git \
            wget \
            libglib2.0-dev \
            libdbus-1-dev \
            libfontconfig1-dev \
            libfreetype-dev \
            libgtk-3-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb-shm0-dev \
            libxrender-dev \
            libxcb-cursor-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-randr0-dev \
            libxcb-render-util0-dev \
            libxcb-shape0-dev \
            libxcb-sync-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-xkb-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libxext-dev libxfixes-dev libxrandr-dev libxcomposite-dev \
            libxcursor-dev libxdamage-dev libxtst-dev libglu1-mesa-dev \
            libxcb-util0-dev libgbm-dev libxcb-dri3-dev libxcb-present-dev libxcb-glx0-dev \
            libssl-dev libxcb-render0-dev libsm-dev \
            libwayland-dev \
            libwayland-egl-backend-dev \
            libxcb-ewmh-dev

      - name: Download qtbase source only
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.9/6.9.0/submodules/qtbase-everywhere-src-6.9.0.tar.xz
          tar xf qtbase-everywhere-src-6.9.0.tar.xz

      - name: Configure and build qtbase statically
        run: |
          mkdir qtbase-build
          cd qtbase-build
          cmake -GNinja ../qtbase-everywhere-src-6.9.0 \
            -DCMAKE_INSTALL_PREFIX=../qtbase-static-install \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DQT_BUILD_EXAMPLES=OFF \
            -DQT_BUILD_TESTS=OFF \
            -DQT_BUILD_INTERNALS=ON \
            -DFEATURE_dbus=ON \
            -DFEATURE_icu=ON \
            -DFEATURE_opengl=ON \
            -DFEATURE_png=ON \
            -DFEATURE_jpeg=ON \
            -DFEATURE_freetype=ON \
            -DFEATURE_harfbuzz=ON \
            -DQT_FEATURE_gui=ON \
            -DQT_FEATURE_widgets=ON \
            -DINPUT_xcb=ON \
            -DQT_FEATURE_xlib=ON \
            -DQT_FEATURE_xcb=ON \
            -DQT_FEATURE_xcb_xlib=ON \
            -DFEATURE_system_zlib=OFF \
            -DFEATURE_system_png=OFF \
            -DFEATURE_system_jpeg=OFF \
            -DFEATURE_system_freetype=OFF \
            -DFEATURE_system_harfbuzz=OFF

          cmake --build . --parallel
          cmake --install .

      # …（Qt のビルド・インストールステップの直後に）…

      # …（前のステップの直後に追加）…

      - name: Patch Qt6GuiTargets.cmake to pull in XcbQpaPrivateTargets
        run: |
          TGT_FILE="qtbase-static-install/lib/cmake/Qt6Gui/Qt6GuiTargets.cmake"
          echo "🔧 Patching $TGT_FILE to include XcbQpaPrivateTargets…"
          # Qt6GuiTargets.cmake の先頭（または適切な場所）にインクルードを挿入
          sed -i '1i\
          include("${CMAKE_CURRENT_LIST_DIR}/../Qt6XcbQpaPrivate/Qt6XcbQpaPrivateTargets.cmake")' "$TGT_FILE"

      - name: Verify Qt6::XcbQpaPrivate is now export‑ed
        run: |
          grep -R "Qt6::XcbQpaPrivate" qtbase-static-install/lib/cmake/Qt6Gui/Qt6GuiTargets.cmake \
            && echo "✅ Qt6::XcbQpaPrivate が Qt6GuiTargets.cmake に登録されました。" \
            || (echo "❌ まだ定義が見つかりません…"; exit 1)


      - name: Patch Qt6GuiConfig.cmake to register XcbQpaPrivate
        run: |
          GUI_CFG=qtbase-static-install/lib/cmake/Qt6Gui/Qt6GuiConfig.cmake
          echo "🔧 Patching $GUI_CFG to pull in XcbQpaPrivate…" 
          # 挿入位置は「targets を include する直前」
          sed -i '/include("${CMAKE_CURRENT_LIST_DIR}\/Qt6GuiTargets.cmake")/i \
          find_dependency(Qt6XcbQpaPrivate REQUIRED)' "$GUI_CFG"

      - name: Verify patch applied
        run: |
          grep -C2 XcbQpaPrivate qtbase-static-install/lib/cmake/Qt6Gui/Qt6GuiConfig.

      - name: Verify XcbQpaPrivate CMake module exists
        run: |
          if [ ! -f qtbase-static-install/lib/cmake/Qt6XcbQpaPrivate/Qt6XcbQpaPrivateConfig.cmake ]; then
            echo "❌ Qt6XcbQpaPrivateConfig.cmake not copied!"
            exit 1
          fi
          if [ ! -f qtbase-static-install/lib/cmake/Qt6XcbQpaPrivate/Qt6XcbQpaPrivateTargets.cmake ]; then
            echo "❌ Qt6XcbQpaPrivateTargets.cmake not copied!"
            exit 1
          fi
          echo "✅ Qt6XcbQpaPrivate CMake modules in place"

      - name: Check for libqxcb.a presence
        run: |
          if [ ! -f qtbase-static-install/plugins/platforms/libqxcb.a ]; then
            echo "Error: libqxcb.a not found in plugins/platforms"
            find qtbase-static-install -name "libqxcb.a"
            exit 1
          fi
          echo "Success: libqxcb.a found."
          echo "Located libqxcb.a:"
          find qtbase-static-install -name "libqxcb.a"

      - name: Check Qt6GuiConfig.cmake exists
        run: |
          CONFIG_PATH="qtbase-static-install/lib/cmake/Qt6Gui/Qt6GuiConfig.cmake"
          if [ -f "$CONFIG_PATH" ]; then
            echo "✅ Found: $CONFIG_PATH"
          else
            echo "❌ Not found: $CONFIG_PATH"
            exit 1
          fi

#      - name: Check if Qt6::XcbQpaPrivate is defined in Qt6GuiTargets.cmake
#        run: |
#          TARGETS_PATH="qtbase-static-install/lib/cmake/Qt6Gui/Qt6GuiTargets.cmake"
#          if [ ! -f "$TARGETS_PATH" ]; then
#            echo "❌ Qt6GuiTargets.cmake not found at $TARGETS_PATH"
#            exit 1
#          fi
#
#          if grep -q "Qt6::XcbQpaPrivate" "$TARGETS_PATH"; then
#            echo "✅ Qt6::XcbQpaPrivate is defined in $TARGETS_PATH"
#          else
#            echo "❌ Qt6::XcbQpaPrivate is NOT defined in $TARGETS_PATH"
#            exit 1
#          fi

      - name: Package QtBase
        run: |
          cd qtbase-build
          tar -czf qtbase-6.9.0-linux-static.tar.gz ../qtbase-static-install

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qtbase-6.9.0-static-linux
          name: QtBase 6.9.0 Static Linux
          files: qtbase-build/qtbase-6.9.0-linux-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
