name: macOS Build Qt 6.9 Static and Upload to Release (macOS Universal, qt-cmake)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Install dependencies (Xcode + brew packages)
        run: |
          brew install cmake ninja perl python3 pkg-config

      - name: Download qtbase source only
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.9/6.9.0/submodules/qtbase-everywhere-src-6.9.0.tar.xz
          tar xf qtbase-everywhere-src-6.9.0.tar.xz

      - name: Configure and build qtbase statically (Universal)
        run: |
          mkdir qt-build
          cd qt-build
          cmake -GNinja ../qtbase-everywhere-src-6.9.0 \
            -DCMAKE_INSTALL_PREFIX=../qt6-static-install \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DQT_BUILD_EXAMPLES=OFF \
            -DQT_BUILD_TESTS=OFF \
            -DQT_FEATURE_dbus=OFF \
            -DQT_FEATURE_icu=OFF \
            -DQT_FEATURE_opengl=ON \
            -DQT_FEATURE_gui=ON \
            -DQT_FEATURE_widgets=ON \
            -DQT_FEATURE_fontconfig=OFF \
            -DFEATURE_system_zlib=OFF \
            -DFEATURE_system_png=OFF \
            -DFEATURE_system_jpeg=OFF \
            -DFEATURE_system_freetype=OFF \
            -DFEATURE_system_harfbuzz=OFF

          cmake --build . --parallel
          cmake --install .

      - name: Package QtBase (universal)
        run: |
          cd qt-build
          tar -czf qtbase-6.9.0-macos-universal-static.tar.gz ../qt6-static-install

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qtbase-6.9.0-static-macos-14-universal
          name: QtBase 6.9.0 Static macOS Universal
          files: qt-build/qtbase-6.9.0-macos-universal-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}