name: Build QtBase 6.9.0 Static and Upload to Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgl1-mesa-dev \
            libxcb-icccm4-dev \
            libxcb-xinput-dev \
            ninja-build \
            python3 \
            perl \
            cmake \
            curl \
            git \
            wget \
            libglib2.0-dev \
            libdbus-1-dev \
            libfontconfig1-dev \
            libfreetype-dev \
            libgtk-3-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb-shm0-dev \
            libxrender-dev \
            libxcb-cursor-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-randr0-dev \
            libxcb-render-util0-dev \
            libxcb-shape0-dev \
            libxcb-sync-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-xkb-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libxext-dev libxfixes-dev libxrandr-dev libxcomposite-dev \
            libxcursor-dev libxdamage-dev libxtst-dev libglu1-mesa-dev \
            libxcb-util0-dev libgbm-dev libxcb-dri3-dev libxcb-present-dev libxcb-glx0-dev \
            libssl-dev libxcb-render0-dev libsm-dev \
            libwayland-dev \
            libwayland-egl-backend-dev \
            libxcb-ewmh-dev

      - name: Download qtbase source only
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.9/6.9.0/submodules/qtbase-everywhere-src-6.9.0.tar.xz
          tar xf qtbase-everywhere-src-6.9.0.tar.xz

      - name: Configure and build qtbase statically
        run: |
          mkdir qtbase-build
          cd qtbase-build

          cmake -GNinja ../qtbase-everywhere-src-6.9.0 \
            -DCMAKE_INSTALL_PREFIX=../qtbase-static-install \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DQT_BUILD_EXAMPLES=OFF \
            -DQT_BUILD_TESTS=OFF \
            -DFEATURE_dbus=ON \
            -DFEATURE_icu=ON \
            -DFEATURE_opengl=ON \
            -DFEATURE_png=ON \
            -DFEATURE_jpeg=ON \
            -DFEATURE_freetype=ON \
            -DFEATURE_harfbuzz=ON \
            -DQT_FEATURE_xlib=ON \
            -DQT_FEATURE_xcb=ON \
            -DQT_FEATURE_xcb_xlib=ON \
            -DFEATURE_system_zlib=OFF \
            -DFEATURE_system_png=OFF \
            -DFEATURE_system_jpeg=OFF \
            -DFEATURE_system_freetype=OFF \
            -DFEATURE_system_harfbuzz=OFF

          cmake --build . --parallel
          cmake --install .

      - name: Package QtBase
        run: |
          cd qtbase-build
          tar -czf qtbase-6.9.0-linux-static.tar.gz ../qtbase-static-install

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qtbase-6.9.0-static-linux
          name: QtBase 6.9.0 Static Linux
          files: qtbase-build/qtbase-6.9.0-linux-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}