name: Build Static Qt with Dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      STATIC_PREFIX: /opt/static
      PKG_CONFIG_PATH: /opt/static/lib/pkgconfig
      CFLAGS: -I/opt/static/include
      LDFLAGS: -L/opt/static/lib

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libtool \
            autoconf \
            automake \
            cmake \
            gettext \
            git \
            wget \
            meson \
            ninja-build \
            python3-pip

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            autoconf automake libtool \
            pkg-config cmake \
            git wget unzip \
            libgl1-mesa-dev
            
      - name: Create static install dir
        run: sudo mkdir -p /opt/static && sudo chown $USER:$USER /opt/static

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libtool \
            autoconf \
            automake \
            cmake \
            gettext \
            git \
            wget

      # zlib
      - name: Build zlib (static)
        run: |
          wget https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz
          tar xf zlib-1.3.1.tar.gz
          cd zlib-1.3.1
          ./configure --static --prefix=/opt/static
          make -j$(nproc)
          make install

      # libpng
      - name: Build libpng (static)
        run: |
          wget https://download.sourceforge.net/libpng/libpng-1.6.43.tar.gz
          tar xf libpng-1.6.43.tar.gz
          cd libpng-1.6.43
          CPPFLAGS="-I/opt/static/include" LDFLAGS="-L/opt/static/lib" \
          ./configure --disable-shared --enable-static --prefix=/opt/static
          make -j$(nproc)
          make install

      # freetype
      - name: Build freetype (static)
        run: |
          wget https://download.savannah.gnu.org/releases/freetype/freetype-2.13.2.tar.gz
          tar xf freetype-2.13.2.tar.gz
          cd freetype-2.13.2
          ./configure --prefix=/opt/static --enable-static --disable-shared \
            --with-png=yes \
            CPPFLAGS="-I/opt/static/include" \
            LDFLAGS="-L/opt/static/lib"
          make -j$(nproc)
          make install

      # harfbuzz
      - name: Build harfbuzz (static)
        run: |
          wget https://github.com/harfbuzz/harfbuzz/releases/download/8.3.0/harfbuzz-8.3.0.tar.xz
          tar xf harfbuzz-8.3.0.tar.xz
          cd harfbuzz-8.3.0
          mkdir build && cd build
          meson .. \
            --prefix=/opt/static \
            --buildtype=release \
            --with-pkgconfigdir=/opt/static/lib/pkgconfig \
            -Ddefault_library=static \
            -Dfreetype=enabled \
            -Dglib=disabled \
            -Dgobject=disabled \
            -Dicu=disabled \
            -Dtests=disabled \
            -Ddocs=disabled

          ninja
          ninja install

      - name: Download Qt 6.9 source
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.9/6.9.0/single/qt-everywhere-src-6.9.0.tar.xz
          tar xf qt-everywhere-src-6.9.0.tar.xz

      - name: Configure and build Qt static
        run: |
          mkdir qt-build
          cd  qt-build
          ../qt-everywhere-src-6.9.0/configure \
            -prefix ../qt-build/qt6-static-install \
            -static \
            -release \
            -opensource -confirm-license \
            -nomake examples -nomake tests \
            -skip qt3d -skip qtwebengine -skip qtwebchannel -skip qtwebview \
            -skip qtcharts -skip qtvirtualkeyboard \
            -skip qtlocation -skip qtsensors -skip qtlottie \
            -skip qtconnectivity -skip qtdoc -skip qttranslations \
            -no-pch \
            -system-harfbuzz -system-libpng -system-freetype \
            -platform linux-g++ \
            -c++std c++20 \
            -I${{ env.STATIC_PREFIX }}/include \
            -L${{ env.STATIC_PREFIX }}/lib
          make -j$(nproc)
          make install
          
      - name: Package Qt
        run: |
          cd qt-build
          tar -czf qt6.9.0-linux-static.tar.gz qt6-static-install
          
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt6.9.0-static-linux
          name: Qt 6.9.0 Static Linux
          files: qt-build/qt6.9.0-linux-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
