name: Build Qt 6.5 Static and Upload to Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgl1-mesa-dev \
            libxcb-xinerama0-dev \
            libxkbcommon-dev \
            libxcb-cursor-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-render-util0-dev \
            libxcb-xinput-dev \
            libxcb-xfixes0-dev \
            ninja-build \
            python3 \
            perl \
            cmake \
            curl \
            git

      - name: Download Qt 6.5 source
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.5/6.5.0/single/qt-everywhere-src-6.5.0.tar.xz
          tar xf qt-everywhere-src-6.5.0.tar.xz

      - name: Configure and build Qt statically
        run: |
          mkdir qt-build
          cd qt-build
          ../qt-everywhere-src-6.5.0/configure \
            -prefix $PWD/qt6-static-install \
            -static \
            -release \
            -nomake examples \
            -nomake tests \
            -skip qtwebengine \
            -opensource -confirm-license \
            -platform linux-g++
          cmake --build . --parallel $(nproc)
          cmake --install .

      - name: Package Qt
        run: |
          cd qt-build
          tar -czf qt6.5.0-linux-static.tar.gz qt6-static-install

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt6.5.0-static-linux
          name: Qt 6.5.0 Static Linux
          files: qt-build/qt6.5.0-linux-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}