name: Build QT5 CaptureStream2 with MXE

on:
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mxe-builder repository
        uses: actions/checkout@v4

      - name: Clone CaptureStream2 repository
        run: |
          git clone --depth=1 https://github.com/CSReviser/CaptureStream2.git app

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Download MXE artifact from Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download  mxe-qt5-v1 \
            --repo ${{ github.repository }} \
            --pattern "mxe-x86_64-w64-mingw32.static.tar.gz"

      - name: Extract MXE environment
        run: |
          mkdir mxe
          tar -xzf mxe-x86_64-w64-mingw32.static.tar.gz

      - name: Build CaptureStream2 with MXE
        run: |
          export PATH=$(pwd)/mxe/usr/bin:$PATH
          export QT_QMAKE=$MXE_PATH/usr/x86_64-w64-mingw32.static/qt5/bin/qmake
          cd app
          mkdir build
          cd build
          $QT_QMAKE
          make -j$(nproc)

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: capturestream2-windows-qt5
          path: app/build/*.exe