name: Build CaptureStream2 with Qt ${{ env.QT_VERSION }} Static

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.8.3

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            # （中略：依存パッケージのリストはそのままでOK）

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git submodule update --init --recursive

      - name: Download and extract Qt ${{ env.QT_VERSION }} static build
        run: |
          curl -LO https://github.com/CSReviser/mxe-builder/releases/download/qt${{ env.QT_VERSION }}-static-linux/qt${{ env.QT_VERSION }}-linux-static.tar.gz
          tar -xf qt${{ env.QT_VERSION }}-linux-static.tar.gz

      - name: Build CaptureStream2 with static Qt using qt-cmake
        run: |
          cd CaptureStream2
          mkdir build && cd build
          ../../qt6-static-install/bin/qt-cmake .. -DQT_DEBUG_FIND_PACKAGE=ON
          cmake --build . --parallel

      - name: Archive result
        run: |
          cd CaptureStream2/build
          tar -czf capturestream2-linux-static.tar.gz CaptureStream2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: capturestream2-linux-static
          path: CaptureStream2/build/capturestream2-linux-static.tar.gz