name: Build QtBase 6.9.0 Static and Upload to Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgl1-mesa-dev \
            libxcb-icccm4-dev \
            libxcb-xinput-dev \
            ninja-build \
            python3 \
            perl \
            cmake \
            curl \
            git \
            wget \
            libglib2.0-dev \
            libdbus-1-dev \
            libfontconfig1-dev \
            libfreetype-dev \
            libgtk-3-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb-shm0-dev \
            libxrender-dev \
            libxcb-cursor-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-randr0-dev \
            libxcb-render-util0-dev \
            libxcb-shape0-dev \
            libxcb-sync-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-xkb-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libxext-dev libxfixes-dev libxrandr-dev libxcomposite-dev \
            libxcursor-dev libxdamage-dev libxtst-dev libglu1-mesa-dev \
            libxcb-util0-dev libgbm-dev libxcb-dri3-dev libxcb-present-dev \
            libssl-dev libxcb-render0-dev libsm-dev \
            libwayland-dev \
            libxcb1-dev \
            libxcb-render0-dev \
            libxcb-xinerama0-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-glx0-dev \
            libxcb-present-dev \
            libxcb-dri2-0-dev \
            libxcb-dri3-dev \
            libxcb-util-dev \
            libxi-dev \
            libxfixes-dev \
            libxcb-composite0-dev \
            libxcb-damage0-dev \
            libxcb-dpms0-dev \
            libxcb-record0-dev \
            libxcb-res0-dev \
            libxcb-screensaver0-dev \
            libxcb-xtest0-dev \
            libxcb-xvmc0-dev \
            libwayland-egl-backend-dev \
            libxcb-ewmh-dev \
            pkg-config \
            libxcb-dri2-0-dev \
            libatspi2.0-dev
            
      - name: Download qtbase source only
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtbase-everywhere-src-6.8.3.tar.xz
          tar xf qtbase-everywhere-src-6.8.3.tar.xz

      - name: Configure and build qtbase statically
        run: |
          mkdir qt-build
          cd qt-build
          cmake -GNinja ../qtbase-everywhere-src-6.8.3 \
            -DCMAKE_INSTALL_PREFIX=../qt6-static-install \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DQT_BUILD_EXAMPLES=OFF \
            -DQT_BUILD_TESTS=OFF \
            -DFEATURE_dbus=ON \
            -DFEATURE_icu=ON \
            -DFEATURE_opengl=ON \
            -DFEATURE_png=ON \
            -DFEATURE_jpeg=ON \
            -DFEATURE_freetype=ON \
            -DFEATURE_harfbuzz=ON \
            -DQT_FEATURE_gui=ON \
            -DQT_FEATURE_widgets=ON \
            -DINPUT_xcb=ON \
            -DQT_FEATURE_xlib=ON \
            -DQT_FEATURE_xcb=ON \
            -DQT_FEATURE_xcb_xlib=ON \
            -DQT_FEATURE_xkbcommon=ON \
            -DQT_FEATURE_fontconfig=ON \
            -DQT_FEATURE_sessionmanager=ON \
            -DQT_FEATURE_glib=ON \
            -DQT_FEATURE_xrender=ON \
            -DFEATURE_system_zlib=OFF \
            -DFEATURE_system_png=OFF \
            -DFEATURE_system_jpeg=OFF \
            -DFEATURE_system_freetype=OFF \
            -DFEATURE_system_harfbuzz=OFF

          cmake --build . --parallel
          cmake --install .

      - name: Verify include of XcbQpaPrivateTargets
        run: |
          TGT_FILE="qt6-static-install/lib/cmake/Qt6Gui/Qt6GuiTargets.cmake"
          if grep -q 'include("${CMAKE_CURRENT_LIST_DIR}/../Qt6XcbQpaPrivate/Qt6XcbQpaPrivateTargets.cmake")' "$TGT_FILE"; then
            echo "✅ Qt6XcbQpaPrivateTargets.cmake is now included in Qt6GuiTargets.cmake"
          else
            echo "❌ Include line not found in $TGT_FILE"
          fi

      - name: Verify XcbQpaPrivate CMake module exists
        run: |
          if [ ! -f qt6-static-install/lib/cmake/Qt6XcbQpaPrivate/Qt6XcbQpaPrivateConfig.cmake ]; then
            echo "❌ Qt6XcbQpaPrivateConfig.cmake not copied!"
          fi
          if [ ! -f qt6-static-install/lib/cmake/Qt6XcbQpaPrivate/Qt6XcbQpaPrivateTargets.cmake ]; then
            echo "❌ Qt6XcbQpaPrivateTargets.cmake not copied!"
          fi
          echo "✅ Qt6XcbQpaPrivate CMake modules in place"

      - name: Check for libqxcb.a presence
        run: |
          if [ ! -f qt6-static-install/plugins/platforms/libqxcb.a ]; then
            echo "Error: libqxcb.a not found in plugins/platforms"
            find qt6-static-install -name "libqxcb.a"
          fi
          echo "Success: libqxcb.a found."
          echo "Located libqxcb.a:"
          find qt6-static-install -name "libqxcb.a"

      - name: Check Qt6GuiConfig.cmake exists
        run: |
          CONFIG_PATH="qt6-static-install/lib/cmake/Qt6Gui/Qt6GuiConfig.cmake"
          if [ -f "$CONFIG_PATH" ]; then
            echo "✅ Found: $CONFIG_PATH"
          else
            echo "❌ Not found: $CONFIG_PATH"
          fi

      - name: Check if Qt6::XcbQpaPrivate is defined in Qt6GuiTargets.cmake
        run: |
          TARGETS_PATH="qt6-static-install/lib/cmake/Qt6Gui/Qt6GuiTargets.cmake"
          if [ ! -f "$TARGETS_PATH" ]; then
            echo "❌ Qt6GuiTargets.cmake not found at $TARGETS_PATH"
          fi

          if grep -q "Qt6::XcbQpaPrivate" "$TARGETS_PATH"; then
            echo "✅ Qt6::XcbQpaPrivate is defined in $TARGETS_PATH"
          else
            echo "❌ Qt6::XcbQpaPrivate is NOT defined in $TARGETS_PATH"
          fi

      - name: Package QtBase
        run: |
          cd qt-build
          tar -czf qtbase-6.8.3-linux-static.tar.gz ../qt6-static-install

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qtbase-6.8.3-static-ubuntu-22.04
          name: QtBase 6.8.3 Static Linux
          files: qt-build/qtbase-6.8.3-linux-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
