name: Build MXE and Upload to Releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              autoconf \
              automake \
              autopoint \
              bash \
              bison \
              bzip2 \
              flex \
              g++ \
              g++-multilib \
              gettext \
              git \
              gperf \
              intltool \
              libc6-dev-i386 \
              libclang-dev \
              libgdk-pixbuf2.0-dev \
              libltdl-dev \
              libgl-dev \
              libpcre2-dev \
              libssl-dev \
              libtool-bin \
              libxml-parser-perl \
              lzip \
              make \
              openssl \
              p7zip-full \
              patch \
              perl \
              python3 \
              python3-mako \
              python3-packaging \
              python3-pkg-resources \
              python3-setuptools \
              python-is-python3 \
              ruby \
              sed \
              sqlite3 \
              unzip \
              wget \
              xz-utils

      - name: Build MXE
        run: |
          git clone https://github.com/mxe/mxe.git
          cd mxe
          make qtbase qttools qtscript cmake MXE_TARGETS='x86_64-w64-mingw32.static' -j$(nproc)

      - name: Package MXE
        run: |
          tar -czf mxe-x86_64-w64-mingw32.static.tar.gz mxe

      - name: Create GitHub Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: mxe-qt5-v1
          name: MXE Qt5 v1
          files: mxe-x86_64-w64-mingw32.static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
