name: Build CS2 ubuntu22 with Qt Static

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.8.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            build-essential \
            cmake \
            ninja-build \
            libgl1-mesa-dev \
            libxcb1-dev \
            libx11-xcb-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-render-util0-dev \
            libxcb-xfixes0-dev \
            libxcb-shape0-dev \
            libxcb-randr0-dev \
            libxcb-sync-dev \
            libxcb-xinerama0-dev \
            libxkbcommon-x11-dev \
            libfontconfig1-dev \
            libfreetype-dev \
            libxrender-dev \
            libx11-dev \
            qt6-base-dev \
            libglib2.0-dev \
            libdbus-1-dev \
            libglib2.0-dev \
            libgtk-3-dev \
            ninja-build \
            libssl-dev \
            libwayland-dev \
            libwayland-egl-backend-dev \
            meson \
            ninja-build \
            python3-pip \
            pkg-config \
            libxcb-dri2-0-dev \
            libglib2.0-dev \
            libdbus-1-dev \
            libfontconfig1-dev \
            libfreetype-dev \
            libgtk-3-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb-shm0-dev \
            libxrender-dev \
            libxcb-cursor-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-randr0-dev \
            libxcb-render-util0-dev \
            libxcb-shape0-dev \
            libxcb-sync-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-xkb-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libxext-dev libxfixes-dev libxrandr-dev libxcomposite-dev \
            libxcursor-dev libxdamage-dev libxtst-dev libglu1-mesa-dev \
            libxcb-util0-dev libgbm-dev libxcb-dri3-dev libxcb-present-dev \
            libssl-dev libxcb-render0-dev libsm-dev \
            libwayland-dev \
            libxcb1-dev \
            libxcb-render0-dev \
            libxcb-xinerama0-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-glx0-dev \
            libxcb-present-dev \
            libxcb-dri2-0-dev \
            libxcb-dri3-dev \
            libxcb-util-dev \
            libxi-dev \
            libxfixes-dev \
            libxcb-composite0-dev \
            libxcb-damage0-dev \
            libxcb-dpms0-dev \
            libxcb-record0-dev \
            libxcb-res0-dev \
            libxcb-screensaver0-dev \
            libxcb-xtest0-dev \
            libxcb-xvmc0-dev \
            libwayland-egl-backend-dev \
            libxcb-ewmh-dev \
            pkg-config \
            libxcb-dri2-0-dev \
            libatspi2.0-dev \
            libgl1-mesa-dev libx11-dev libxext-dev libxrandr-dev libxi-dev libx11-xcb-dev \
            # （中略：依存パッケージのリストはそのままでOK）

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git submodule update --init --recursive

      - name: Download and extract Qt ${{ env.QT_VERSION }} static build
        run: |
          curl -LO https://github.com/CSReviser/mxe-builder/releases/download/qtbase-${{ env.QT_VERSION }}-ubuntu-22.04/qtbase-${{ env.QT_VERSION }}-linux-static.tar.gz
          tar -xf  qtbase-${{ env.QT_VERSION }}-linux-static.tar.gz

      - name: Build CaptureStream2 with static Qt using qt-cmake
        run: |
          cd CaptureStream2
          mkdir build && cd build
          ../../qtbase-static-install/bin/qt-cmake .. -DQT_DEBUG_FIND_PACKAGE=ON
          cmake --build . --parallel

      - name: Archive result
        run: |
          cd CaptureStream2/build
          tar -czf capturestream2-linux-static.tar.gz CaptureStream2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: capturestream2-linux-static
          path: CaptureStream2/build/capturestream2-linux-static.tar.gz
