name: Build MXE Qt6 32bit and Upload to Releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib \
            gettext git gperf intltool libc6-dev-i386 libclang-dev libgdk-pixbuf2.0-dev \
            libltdl-dev libgl-dev libpcre2-dev libssl-dev libtool-bin libxml-parser-perl \
            lzip make openssl p7zip-full patch perl python3 python3-mako python3-packaging \
            python3-pkg-resources python3-setuptools python-is-python3 ruby sed sqlite3 \
            unzip wget xz-utils \
            g++-multilib \
            libc6-dev-i386

      - name: Clone MXE
        run: |
          git clone https://github.com/mxe/mxe.git
          chmod +x ./remove-mariadb.sh
          bash ./remove-mariadb.sh
          grep -rn 'mariadb-connector-c' mxe/
          cd mxe
          git checkout master

      - name: Patch qtbase.mk to skip MariaDB
        run: |
          cat <<'EOF' > qt6-disable-mariadb.patch
          --- a/src/qt/qt6/qt6-qtbase.mk
          +++ b/src/qt/qt6/qt6-qtbase.mk
          @@ -14 +14 @@
          -$(PKG)_DEPS     := cc freetype harfbuzz jpeg libpng mesa mariadb-connector-c openssl pcre2
          +$(PKG)_DEPS     := cc freetype harfbuzz jpeg libpng mesa openssl pcre2
          'EOF'
          
            patch -p1 -d mxe < qt6-disable-mariadb.patch


      - name: Build MXE with Qt6 (32bit static)
        run: |
          cd mxe
          make qt6-qtbase qt6-qttools gcc cmake MXE_TARGETS='i686-w64-mingw32.static' -j$(nproc)

      - name: Package MXE Qt6 32bit
        run: |
          find ./ -type f \( -name "*.cmake" -o -name "*.pri" -o -name "*.la" -o -name "*.pc" \) -exec sed -i 's|/home/runner/work/mxe-builder/mxe-builder/mxe|/mxe|g' {} +
          tar -czf mxe-qt6-i686-static.tar.gz mxe

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: mxe-qt6-i686-v1
          name: MXE Qt6 32bit Static v1
          files: mxe-qt6-i686-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
