name: Build MXE Qt5 32bit and Upload to Releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              autoconf \
              automake \
              autopoint \
              bash \
              bison \
              bzip2 \
              flex \
              g++ \
              g++-multilib \
              gettext \
              git \
              gperf \
              intltool \
              libc6-dev-i386 \
              libclang-dev \
              libgdk-pixbuf2.0-dev \
              libltdl-dev \
              libgl-dev \
              libpcre2-dev \
              libssl-dev \
              libtool-bin \
              libxml-parser-perl \
              lzip \
              make \
              openssl \
              p7zip-full \
              patch \
              perl \
              python3 \
              python3-mako \
              python3-packaging \
              python3-pkg-resources \
              python3-setuptools \
              python-is-python3 \
              ruby \
              sed \
              sqlite3 \
              unzip \
              wget \
              xz-utils

      - name: Clone MXE
        run: git clone https://github.com/mxe/mxe.git

      - name: Apply patch to disable mariadb-connector-c
        working-directory: ./mxe
        run: |
    cat << 'EOF' > ../qtbase-no-mariadb.patch
--- a/src/qtbase.mk
+++ b/src/qtbase.mk
@@
 $(PKG)_DEPS := zlib libpng freetype fontconfig sqlite libjpeg \
-              dbus libicu pcre2 harfbuzz xz libxml2 \
-              $(if $(filter $(MXE_WINDOWS_BUILD),y), \
-                   openssl libmysqlclient)
+              dbus libicu pcre2 harfbuzz xz libxml2 \
+              $(if $(filter $(MXE_WINDOWS_BUILD),y), \
+                   openssl)
EOF
    patch -p1 < ../qtbase-no-mariadb.patch
      - name: Build MXE with Qt5 (32bit)
        run: |
          cd mxe
          export qtbase_SKIP_MARIADB=1
          make qtbase \
          MXE_TARGETS='i686-w64-mingw32.static' \
          qtbase_CONFIGURE_OPTS='-no-sql-mysql -no-sql-odbc' \
          -j$(nproc)
        continue-on-error: true

      - name: Show mariadb-connector-c build log
        if: always()
        run: |
          cat mxe/log/mariadb-connector-c_i686-w64-mingw32.static || echo "Log not found"

#      - name: Build MXE with Qt5 (32bit)
#        run: |
#          cd mxe
#          export qtbase_SKIP_MARIADB=1
#          make qtbase MXE_TARGETS='i686-w64-mingw32.static' -j$(nproc)

#      - name: Print mariadb build log
#        run: cat mxe/log/mariadb-connector-c_i686-w64-mingw32.static
      - name: Package MXE Qt5 32bit
        run: |
          tar -czf mxe-qt5-i686-static.tar.gz mxe

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: mxe-qt5-i686-v1
          name: MXE Qt5 32bit Static v1
          files: mxe-qt5-i686-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
