name: macOS Build Qt 6.9 Static and Upload to Release (macOS Universal, qt-cmake)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Install dependencies (via Homebrew)
        run: |
          brew update
          brew install \
            cmake \
            ninja \
            perl \
            python3 \
            pkg-config \
            freetype \
            fontconfig \
            libpng \
            jpeg \
            zlib \
            pcre2 \
            harfbuzz \
            wget \
            git

      - name: Download Qt 6.9 source
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.9/6.9.0/single/qt-everywhere-src-6.9.0.tar.xz
          tar xf qt-everywhere-src-6.9.0.tar.xz

      - name: Configure and build Qt statically (universal)
        run: |
          mkdir qt-build
          cd qt-build
          ../qt-everywhere-src-6.9.0/configure \
            -prefix ../qt-build/qt6-static-install \
            -static -static-runtime \
            -release \
            -opensource -confirm-license \
            -nomake examples -nomake tests \
            -skip qt3d -skip qtwebengine -skip qtwebchannel -skip qtwebview \
            -skip qtcharts -skip qtvirtualkeyboard \
            -skip qtlocation -skip qtsensors -skip qtlottie \
            -skip qtconnectivity -skip qtdoc -skip qttranslations \
            -no-pch \
            -qt-harfbuzz \
            -qt-freetype \
            -qt-libpng \
            -qt-zlib \
            -qt-libjpeg \
            -qt-pcre \
            -qt-doubleconversion \
            -platform macx-clang \
            -c++std c++20 \
            -device-option QMAKE_APPLE_DEVICE_ARCHS=arm64,x86_64

          cmake --build . --parallel
          cmake --install .

      - name: Package Qt
        run: |
          cd qt-build
          tar -czf qt6.9.0-macos-universal-static.tar.gz qt6-static-install

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt6.9.0-static-macos-universal
          name: Qt 6.9.0 Static macOS Universal
          files: qt-build/qt6.9.0-macos-universal-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}