name: CS2 static-ubuntu　ubuntu22 with Qt Static (Docker)

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.9.0
  IMAGE_NAME: ghcr.io/csreviser/qt6-static-ubuntu:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git checkout feature
          git submodule update --init --recursive
      - name: Get UID and GID
        id: userinfo
        run: |
          echo "uid=$(id -u)" >> "$GITHUB_OUTPUT"
          echo "gid=$(id -g)" >> "$GITHUB_OUTPUT"
      - name: Build using Docker container with Qt static
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/work \
            -w /work/CaptureStream2 \
            --env HOST_UID=${{ steps.userinfo.outputs.uid }} \
            --env HOST_GID=${{ steps.userinfo.outputs.gid }} \
            --env PATH="/opt/qt6-static/bin:/usr/bin:/bin:/usr/local/bin" \
            ${{ env.IMAGE_NAME }} \
            bash -c "
              mkdir -p build && cd build && \
              qt-cmake .. -DQT_DEBUG_FIND_PACKAGE=ON && \
              cmake --build . --parallel && \
              mkdir -p build/LinCaptureStream2 && \
              mv CaptureStream2 build/LinCaptureStream2/ && \
              cp ../qss_files/stylesheet-ubu.qss build/LinCaptureStream2 && \
              chown -R \$HOST_UID:\$HOST_GID /work
            "
            
      - name: Archive result
        run: |
          cd CaptureStream2
          ls -r
          cd build
          ls -r
          tar -czf capturestream2-linux-static.tar.gz CaptureStream2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: capturestream2-linux-static
          path: CaptureStream2/build/capturestream2-linux-static.tar.gz
