name: CS2 ubuntu22 with Qt Static (Docker)

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.9.0
  IMAGE_NAME: ghcr.io/csreviser/qt6-ubuntu-static:latest

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git submodule update --init --recursive

      - name: Get UID and GID
        id: userinfo
        run: |
          echo "uid=$(id -u)" >> "$GITHUB_OUTPUT"
          echo "gid=$(id -g)" >> "$GITHUB_OUTPUT"

      - name: Build using Docker container with Qt static
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/work \
            -w /work/CaptureStream2 \
            --env HOST_UID=${{ steps.userinfo.outputs.uid }} \
            --env HOST_GID=${{ steps.userinfo.outputs.gid }} \
            --env PATH="/opt/qt6-static/bin:/usr/bin:/bin:/usr/local/bin" \
            ${{ env.IMAGE_NAME }} \
            bash -c "
              mkdir -p build && cd build && \
              qt-cmake .. &&\
              cmake --build . --parallel \
              -DCMAKE_EXE_LINKER_FLAGS="-lxml2 -lfreetype -lxcb-util" && \
              chown -R \$HOST_UID:\$HOST_GID /work
            "

      - name: Archive result
        run: |
          cd CaptureStream2/build
          tar -czf capturestream2-linux-static.tar.gz CaptureStream2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: capturestream2-linux-static
          path: CaptureStream2/build/capturestream2-linux-static.tar.gz
