name: Build Qt Static + CaptureStream2

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-qt:
    runs-on: ubuntu-latest
    name: Build Qt 6.9 Static

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgl1-mesa-dev \
            libxcb-xinerama0-dev \
            libxkbcommon-dev \
            libxcb-cursor-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-render-util0-dev \
            libxcb-xinput-dev \
            libxcb-xfixes0-dev \
            ninja-build \
            python3 \
            perl \
            cmake \
            curl \
            git \
            libfontconfig1-dev \
            libfreetype-dev \
            libgtk-3-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb-randr0-dev \
            libxcb-shape0-dev \
            libxcb-shm0-dev \
            libxcb-sync-dev \
            libxrender-dev \
            libharfbuzz-dev \
            libpng-dev

      - name: Download Qt 6.9 source
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.9/6.9.0/single/qt-everywhere-src-6.9.0.tar.xz
          tar xf qt-everywhere-src-6.9.0.tar.xz

      - name: Configure and build Qt statically
        run: |
          mkdir qt-build
          cd qt-build
          ../qt-everywhere-src-6.9.0/configure \
            -prefix $PWD/qt6-static-install \
            -static \
            -release \
            -nomake examples \
            -nomake tests \
            -opensource -confirm-license \
            -skip qtwebengine -skip qtwebchannel -skip qtwebview \
            -skip qtdoc -skip qttranslations \
            -system-harfbuzz -system-libpng -system-freetype \
            -platform linux-g++ \
            -c++std c++20
          cmake --build . --parallel
          cmake --install .

      - name: Package Qt
        run: |
          cd qt-build
          tar -czf qt6.9.0-linux-static.tar.gz qt6-static-install

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt6.9.0-static-linux
          name: Qt 6.9.0 Static Linux
          files: qt-build/qt6.9.0-linux-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-app:
    needs: build-qt
    runs-on: ubuntu-latest
    name: Build CaptureStream2 App

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            libgl1-mesa-dev \
            libx11-dev \
            libxcb1-dev \
            libxcb-glx0-dev \
            libxcb-keysyms1-dev \
            libxcb-image0-dev \
            libxcb-shm0-dev \
            libxcb-icccm4-dev \
            libxcb-sync-dev \
            libxcb-xfixes0-dev \
            libxcb-shape0-dev \
            libxcb-randr0-dev \
            libxcb-render-util0-dev \
            libxcb-xinerama0-dev \
            libx11-xcb-dev \
            libxkbcommon-x11-dev \
            libharfbuzz-dev \
            libfreetype-dev \
            libpng-dev \
            git

      - name: Download Qt from GitHub Releases
        run: |
          curl -LO https://github.com/${{ github.repository }}/releases/download/qt6.9.0-static-linux/qt6.9.0-linux-static.tar.gz
          tar xf qt6.9.0-linux-static.tar.gz

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2

      - name: Build CaptureStream2
        run: |
          cd CaptureStream2
          mkdir build
          cd build
          ../qt6-static-install/bin/qt-cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --parallel