name: Windows Static Build (MXE)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/csreviser/qt6-mxe-static:6.9.0

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake
        run: >
          x86_64-w64-mingw32.static-cmake
          -S .
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH=/opt/qt6-static
          -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32.static
          -DCMAKE_SYSTEM_NAME=Windows
          -DCMAKE_INSTALL_PREFIX=install
          -DQT_HOST_PATH=/opt/qt6-static

      - name: Build
        run: cmake --build build --parallel

      - name: Install
        run: cmake --install build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: capturestream2-windows-static
          path: install/